package am.techshop.product;

import liquibase.Contexts;
import liquibase.Liquibase;
import liquibase.database.Database;
import liquibase.database.DatabaseFactory;
import liquibase.database.jvm.JdbcConnection;
import liquibase.resource.ClassLoaderResourceAccessor;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AddRatingColumnsToProductsMigrationTest {

    @Test
    void changelog_OnAlreadySeededDatabase_BackfillsRatingAndReviewCountToZero() throws Exception {
        String jdbcUrl = "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL";

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "")) {
            connection.createStatement().execute("""
                    CREATE TABLE products (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        description VARCHAR(1000),
                        price DECIMAL(19,2),
                        stock INT,
                        category VARCHAR(255),
                        image_url VARCHAR(500),
                        is_new BOOLEAN,
                        discount_percentage INT,
                        created_at TIMESTAMP
                    )
                    """);
            connection.createStatement().execute(
                    "INSERT INTO products (name, description, price, stock, category, image_url, is_new, discount_percentage, created_at) "
                            + "VALUES ('iPhone 15, 128GB', 'Apple iPhone 15 with 128GB storage.', 450000.00, 25, 'Phones', "
                            + "'https://images.unsplash.com/photo-1736173155811-e8142fd553ee?w=900&q=82&fit=crop&auto=format', true, NULL, CURRENT_TIMESTAMP)");

            Database database = DatabaseFactory.getInstance()
                    .findCorrectDatabaseImplementation(new JdbcConnection(connection));
            Liquibase liquibase = new Liquibase(
                    "db/changelog/db.changelog-master.xml", new ClassLoaderResourceAccessor(), database);
            liquibase.update(new Contexts());

            try (ResultSet rs = connection.createStatement().executeQuery(
                    "SELECT rating, review_count FROM products WHERE name = 'iPhone 15, 128GB'")) {
                assertEquals(true, rs.next());
                assertEquals(0, new java.math.BigDecimal("0.00").compareTo(rs.getBigDecimal("rating")));
                assertEquals(0, rs.getInt("review_count"));
            }

            liquibase.update(new Contexts());
            try (ResultSet rs = connection.createStatement().executeQuery(
                    "SELECT COUNT(*) FROM products WHERE name = 'iPhone 15, 128GB'")) {
                rs.next();
                assertEquals(1, rs.getInt(1));
            }
        }
    }

    @Test
    void changelog_NoOpsCleanlyWhenProductsTableDoesNotExistYet() throws Exception {
        String jdbcUrl = "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL";

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "")) {
            Database database = DatabaseFactory.getInstance()
                    .findCorrectDatabaseImplementation(new JdbcConnection(connection));
            Liquibase liquibase = new Liquibase(
                    "db/changelog/db.changelog-master.xml", new ClassLoaderResourceAccessor(), database);
            liquibase.update(new Contexts());
        }
    }
}
