package am.techshop.product;

import liquibase.Contexts;
import liquibase.Liquibase;
import liquibase.database.Database;
import liquibase.database.DatabaseFactory;
import liquibase.database.jvm.JdbcConnection;
import liquibase.resource.ClassLoaderResourceAccessor;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MockCatalogSeedMigrationTest {

    @Test
    void changelog_BackfillsRemainingMockCatalogProductsWithoutDuplicatingExistingOnes() throws Exception {
        String jdbcUrl = "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL";

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "")) {
            connection.createStatement().execute("""
                    CREATE TABLE products (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        description VARCHAR(1000),
                        price DECIMAL(19,2),
                        stock INT,
                        category VARCHAR(255),
                        image_url VARCHAR(500),
                        is_new BOOLEAN,
                        discount_percentage INT,
                        created_at TIMESTAMP
                    )
                    """);
            connection.createStatement().execute("""
                    CREATE TABLE categories (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) UNIQUE NOT NULL
                    )
                    """);
            connection.createStatement().execute(
                    "INSERT INTO categories (name) VALUES ('Phones'), ('Laptops'), ('TVs'), ('Audio'), ('Cameras')");

            insertExistingProduct(connection, "iPhone 15, 128GB", "Phones");
            insertExistingProduct(connection, "Samsung Galaxy S24", "Phones");
            insertExistingProduct(connection, "iPhone 17 Pro", "Phones");
            insertExistingProduct(connection, "iPhone 17 Pro Max", "Phones");
            insertExistingProduct(connection, "MacBook Air M2", "Laptops");
            insertExistingProduct(connection, "LG 55\" 4K Smart TV", "TVs");
            insertExistingProduct(connection, "Sony WH-1000XM5", "Audio");
            insertExistingProduct(connection, "Canon EOS R50", "Cameras");

            Database database = DatabaseFactory.getInstance()
                    .findCorrectDatabaseImplementation(new JdbcConnection(connection));
            Liquibase liquibase = new Liquibase(
                    "db/changelog/db.changelog-master.xml", new ClassLoaderResourceAccessor(), database);
            liquibase.update(new Contexts());

            assertEquals(68, count(connection, "SELECT COUNT(*) FROM products"));
            assertEquals(9, count(connection, "SELECT COUNT(*) FROM categories"));

            try (ResultSet rs = connection.createStatement().executeQuery(
                    "SELECT name, COUNT(*) c FROM products GROUP BY name HAVING COUNT(*) > 1")) {
                assertTrue(!rs.next(), "no product name should appear more than once");
            }
            for (String skippedName : new String[] {
                    "Samsung Galaxy S24", "MacBook Air M2", "Sony WH-1000XM5", "iPhone 17 Pro", "iPhone 17 Pro Max"
            }) {
                assertEquals(1, count(connection,
                        "SELECT COUNT(*) FROM products WHERE name = '" + skippedName.replace("'", "''") + "'"));
            }

            assertEquals(1, count(connection, "SELECT COUNT(*) FROM products WHERE name = 'iPhone 15 Pro'"));
            try (ResultSet rs = connection.createStatement().executeQuery(
                    "SELECT price, category, image_url FROM products WHERE name = 'iPhone 15 Pro'")) {
                assertTrue(rs.next());
                assertEquals(0, rs.getBigDecimal("price").compareTo(new java.math.BigDecimal("650000.00")));
                assertEquals("Phones", rs.getString("category"));
                assertTrue(rs.getString("image_url").startsWith("https://"));
            }
            Long iphone15ProId = productId(connection, "iPhone 15 Pro");
            assertEquals(3, count(connection,
                    "SELECT COUNT(*) FROM product_storage_options WHERE product_id = " + iphone15ProId));

            assertEquals(1, count(connection, "SELECT COUNT(*) FROM categories WHERE name = 'Tablets'"));
            assertEquals(1, count(connection, "SELECT COUNT(*) FROM products WHERE name = 'iPad Air' AND category = 'Tablets'"));

            try (ResultSet rs = connection.createStatement().executeQuery("SELECT image_url FROM products")) {
                while (rs.next()) {
                    String url = rs.getString(1);
                    assertTrue(url != null && (url.startsWith("http://") || url.startsWith("https://")),
                            "every product image_url should be an absolute URL, was: " + url);
                }
            }

            liquibase.update(new Contexts());
            assertEquals(68, count(connection, "SELECT COUNT(*) FROM products"));
            assertEquals(9, count(connection, "SELECT COUNT(*) FROM categories"));
        }
    }

    private void insertExistingProduct(Connection connection, String name, String category) throws Exception {
        connection.createStatement().execute(
                "INSERT INTO products (name, description, price, stock, category, image_url, is_new, discount_percentage, created_at) "
                        + "VALUES ('" + name.replace("'", "''") + "', 'desc', 100000.00, 5, '" + category + "', "
                        + "'https://images.unsplash.com/photo-placeholder?w=900', false, NULL, CURRENT_TIMESTAMP)");
    }

    private Long productId(Connection connection, String name) throws Exception {
        try (ResultSet rs = connection.createStatement().executeQuery(
                "SELECT id FROM products WHERE name = '" + name.replace("'", "''") + "'")) {
            assertTrue(rs.next(), "product " + name + " should exist");
            return rs.getLong(1);
        }
    }

    private int count(Connection connection, String sql) throws Exception {
        try (ResultSet rs = connection.createStatement().executeQuery(sql)) {
            rs.next();
            return rs.getInt(1);
        }
    }
}
