package am.techshop.product;

import liquibase.Contexts;
import liquibase.Liquibase;
import liquibase.database.Database;
import liquibase.database.DatabaseFactory;
import liquibase.database.jvm.JdbcConnection;
import liquibase.resource.ClassLoaderResourceAccessor;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ProductVariantTablesMigrationTest {

    @Test
    void changelog_CreatesVariantTablesAndSeedsIphone17ProductsAndBackfillsIphone15() throws Exception {
        String jdbcUrl = "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL";

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "")) {
            connection.createStatement().execute("""
                    CREATE TABLE products (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        description VARCHAR(1000),
                        price DECIMAL(19,2),
                        stock INT,
                        category VARCHAR(255),
                        image_url VARCHAR(500),
                        is_new BOOLEAN,
                        discount_percentage INT,
                        created_at TIMESTAMP
                    )
                    """);
            connection.createStatement().execute(
                    "INSERT INTO products (name, description, price, stock, category, image_url, is_new, discount_percentage, created_at) "
                            + "VALUES ('iPhone 15, 128GB', 'Apple iPhone 15 with 128GB storage.', 450000.00, 25, 'Phones', "
                            + "'https://images.unsplash.com/photo-1736173155811-e8142fd553ee?w=900&q=82&fit=crop&auto=format', true, NULL, CURRENT_TIMESTAMP)");

            Database database = DatabaseFactory.getInstance()
                    .findCorrectDatabaseImplementation(new JdbcConnection(connection));
            Liquibase liquibase = new Liquibase(
                    "db/changelog/db.changelog-master.xml", new ClassLoaderResourceAccessor(), database);
            liquibase.update(new Contexts());

            Long proId = productId(connection, "iPhone 17 Pro");
            assertEquals(List.of("256GB", "512GB", "1TB"), storageLabels(connection, proId));
            assertEquals(List.of("Dual eSIM", "Nano-SIM & eSIM"), simValues(connection, proId));
            assertEquals(List.of("Cosmic Orange", "Silver", "Deep Blue"), colorLabels(connection, proId));

            Long proMaxId = productId(connection, "iPhone 17 Pro Max");
            assertEquals(List.of("256GB", "512GB", "1TB"), storageLabels(connection, proMaxId));
            assertEquals(List.of("Dual eSIM", "Nano-SIM & eSIM"), simValues(connection, proMaxId));
            assertEquals(List.of("Cosmic Orange", "Silver", "Deep Blue"), colorLabels(connection, proMaxId));

            for (Long id : List.of(proId, proMaxId)) {
                for (String imageUrl : colorImageUrls(connection, id)) {
                    assertTrue(imageUrl.startsWith("https://prod-cdn.prod.asbis.io/"),
                            "color variant image should be a real ispace.am product photo URL, was: " + imageUrl);
                }
            }

            assertEquals(mainImageUrl(connection, proId), colorImageUrl(connection, proId, "Deep Blue"));
            assertEquals(mainImageUrl(connection, proMaxId), colorImageUrl(connection, proMaxId, "Deep Blue"));

            Long iphone15Id = productId(connection, "iPhone 15, 128GB");
            assertEquals(List.of("128GB", "256GB", "512GB"), storageLabels(connection, iphone15Id));
        }
    }

    @Test
    void changelog_NoOpsCleanlyWhenProductsTableDoesNotExistYet() throws Exception {
        String jdbcUrl = "jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL";

        try (Connection connection = DriverManager.getConnection(jdbcUrl, "sa", "")) {
            Database database = DatabaseFactory.getInstance()
                    .findCorrectDatabaseImplementation(new JdbcConnection(connection));
            Liquibase liquibase = new Liquibase(
                    "db/changelog/db.changelog-master.xml", new ClassLoaderResourceAccessor(), database);
            liquibase.update(new Contexts());
        }
    }

    private Long productId(Connection connection, String name) throws Exception {
        try (ResultSet rs = connection.createStatement().executeQuery(
                "SELECT id FROM products WHERE name = '" + name.replace("'", "''") + "'")) {
            assertTrue(rs.next(), "product " + name + " should exist");
            return rs.getLong(1);
        }
    }

    private List<String> storageLabels(Connection connection, Long productId) throws Exception {
        return column(connection,
                "SELECT label FROM product_storage_options WHERE product_id = " + productId + " ORDER BY sort_order");
    }

    private List<String> simValues(Connection connection, Long productId) throws Exception {
        return column(connection,
                "SELECT sim_value FROM product_sim_options WHERE product_id = " + productId + " ORDER BY sort_order");
    }

    private List<String> colorLabels(Connection connection, Long productId) throws Exception {
        return column(connection,
                "SELECT label FROM product_color_variants WHERE product_id = " + productId + " ORDER BY sort_order");
    }

    private List<String> colorImageUrls(Connection connection, Long productId) throws Exception {
        return column(connection,
                "SELECT image_url FROM product_color_variants WHERE product_id = " + productId + " ORDER BY sort_order");
    }

    private String mainImageUrl(Connection connection, Long productId) throws Exception {
        try (ResultSet rs = connection.createStatement().executeQuery(
                "SELECT image_url FROM products WHERE id = " + productId)) {
            assertTrue(rs.next());
            return rs.getString(1);
        }
    }

    private String colorImageUrl(Connection connection, Long productId, String label) throws Exception {
        try (ResultSet rs = connection.createStatement().executeQuery(
                "SELECT image_url FROM product_color_variants WHERE product_id = " + productId
                        + " AND label = '" + label.replace("'", "''") + "'")) {
            assertTrue(rs.next(), "color variant " + label + " should exist");
            return rs.getString(1);
        }
    }

    private List<String> column(Connection connection, String sql) throws Exception {
        List<String> values = new ArrayList<>();
        try (ResultSet rs = connection.createStatement().executeQuery(sql)) {
            while (rs.next()) {
                values.add(rs.getString(1));
            }
        }
        return values;
    }
}
